sudo: false
language: ruby
cache: bundler

branches:
  only:
    - main

notifications:
  email:
    on_success: never
    on_failure: always
    on_error: always

script: JEKYLL_ENV=production bundle exec jekyll build
